### 레이어 : 신경망 기본 블록

In [1]:
import torch
from torch.nn import Linear, ReLU
import torch.nn as nn
import numpy as np
from torch.autograd import Variable

In [2]:
myLayer = Linear(in_features=10,out_features=5,bias=True)
inp = Variable(torch.randn(1,10))
myLayer = Linear(in_features=10,out_features=5,bias=True) 
myLayer(inp)

tensor([[ 0.3071,  0.6762,  0.2488, -0.3765,  0.1646]],
       grad_fn=<AddmmBackward>)

In [3]:
myLayer.weight

Parameter containing:
tensor([[-0.2375, -0.2135, -0.2007,  0.1291, -0.2373,  0.0368, -0.2187, -0.2600,
          0.1384,  0.1179],
        [-0.1413, -0.1744,  0.2816,  0.2581,  0.0536,  0.2258,  0.0834, -0.1215,
         -0.2303,  0.1810],
        [ 0.0451,  0.2598, -0.3125, -0.0180, -0.1877, -0.2845,  0.2480, -0.1411,
          0.2077,  0.1067],
        [ 0.0654,  0.1747,  0.0648,  0.0328,  0.2393,  0.2067, -0.0353, -0.3022,
          0.1296, -0.2121],
        [ 0.0651,  0.1355,  0.2150,  0.0730,  0.2012, -0.0510,  0.1127, -0.1245,
         -0.1167, -0.1722]], requires_grad=True)

In [4]:
myLayer.bias

Parameter containing:
tensor([ 0.0826, -0.1633,  0.0290, -0.2342,  0.1774], requires_grad=True)

### 선형 레이어 쌓기

In [5]:
myLayer1 = Linear(10,5)
myLayer2 = Linear(5,2)
myLayer2(myLayer1(inp))

tensor([[ 0.1624, -0.7965]], grad_fn=<AddmmBackward>)

### PyTorch 비선형 활성함수

In [6]:
sample_data = Variable(torch.Tensor([[1,2,-1,-1]])) 
myRelu = ReLU()
myRelu(sample_data)


tensor([[1., 2., 0., 0.]])

In [7]:
import torch.nn as nn
import torch.nn.functional as F
sample_data = Variable(torch.Tensor([[1,2,-1,-1]])) 
f = F.relu(sample_data) # Much simpler.
f

tensor([[1., 2., 0., 0.]])

### 신경망

In [8]:
class MyFirstNetwork(nn.Module):
    def __init__(self,input_size,hidden_size,output_size):
        super(MyFirstNetwork,self).__init__() 
        self.layer1 = nn.Linear(input_size,hidden_size) 
        self.layer2 = nn.Linear(hidden_size,output_size)
    def __forward__(self,input): 
        out = self.layer1(input) 
        out = nn.ReLU(out)
        out = self.layer2(out) 
        return out

### 오차(Loss)

In [9]:
loss = nn.MSELoss()
input = Variable(torch.randn(3, 5), requires_grad=True) 
target = Variable(torch.randn(3, 5))
output = loss(input, target)
output.backward()

In [10]:
def cross_entropy(true_label, prediction):
    if true_label == 1:
        return -log(prediction)
    else:
        return -log(1 - prediction)

In [11]:
loss = nn.CrossEntropyLoss()
input = Variable(torch.randn(3, 5), requires_grad=True) 
target = Variable(torch.LongTensor(3).random_(5)) 
output = loss(input, target)
output.backward()

### 옵티마이저

- 예제 코드
```
# 데모 용
import torch.optim as optim
optimizer = optim.SGD(model.parameters(), lr = 0.01)
for input, target in dataset:
    optimizer.zero_grad()
    output = model(input)
    loss = loss_fn(output, target)
    loss.backward()
    optimizer.step()
```